spring.application.name=auth-service
server.port=8081
spring.datasource.url=jdbc:postgresql://BD_Usuarios:5432/sicaeUsuario
spring.datasource.username=UserPapu
spring.datasource.password=Papulin
app.jwtExpirationMs=86400000
app.jwtSecret=4qHQ+mbQG9NfP/6r7v/M0bT2G8dO9pYq3U4n7w6sR5t=